### ISSUE TITLE
Support of parsers in an external process 

### ISSUE THREAD

**Issue by scharf** [dschaefer/antlng#1]
Instead of running parser inside the eclipse, it should be possible to run parsers as external process with an (JSON) API that allows to send the information required to the IDE.

This would allow for using parsers written in _any_ language, provided they support the parser API. 

This was possible 25 years ago when computers were really slow. Why should it not be possible today?

With such an API the parser would be independent of the IDE/editor.

...to bring another dream to life.... ;-)

**Comment by dschaefer** [comment]
Hey Michael. I'd love to solve all problems :) but my focus is on Antlr and will be reusing it's run-time and generated classes as much as possible.

I'm still not convinced that an external parser is going solve more problems than it creates. I'm not sure how you'd do things like keyword highlighting and incremental lexing required to make that fast. I think I can with Antlr.

At the end of the day, I think it would be easier to write an Antlr 4 grammer for a new language than it would be to implement a parser API that does everything we need. We'll see after we get a few examples done.

**Comment by scharf** [comment]
Hi Doug, I see your point, but the future is not a single IDE. There are many IDEs and smart editors that would need good language integrations. Once you define an API then many editors could use it.

SNiFF was running on a sun 3 (which was running at 16Mhz) with its external parser and we had an [emacs integration](https://gist.github.com/scharf/64e8490c0f693c5719a8) which did syntax and keyword highlights by inter process communication. This had actually two external processes: the parser talking to SNiFF and SNiFF talking to emacs. It did not feel slow at all. I don't see any reason why this architecture would be slow today.

 E.g. this was the entire [python parser in lex](https://gist.github.com/scharf/a9e7a1ab41faf0896a96) using a very simple API to send the symbols to the IDE (note the keyword api in [line 209](https://gist.github.com/scharf/a9e7a1ab41faf0896a96#file-gistfile1-txt-L209)).

It was that simple more than 20 years ago, why should it be more complicated today?

And why does the IDE need to fully parse the language? All it needs is to skip over expressions and to extract the symbol information. Plus a bit of logic to code completion. [Codetrails](http://www.codetrails.com) has shown that for good code completion with heuristics work as well as deep code analysis.

For linting the trend is to use external tools, that can run as part of the build process as well.

The trend is microservices, smart editors, running IDE functionality on the command line....

Your approach feels much more like 90ies style monster IDEs, but, it's your project ;-)

**Comment by dschaefer** [comment]
Yes, I know the trend is to regress back to using vi and command-line. It's most unfortunate.

I'm not willing to give up on the promise of capital I - IDE. Many projects now involve multiple languages, especially web applications. Wouldn't it be nice if you could click on a $ajax call on the client JavaScript code and have it show you the Java microservice that provides that route? Why would you not want that?

Same thing as clicking a QML QtObject call and have it show you the C++ implementation of that call.

So yeah, the Sublime lovers can carry on. I'm trying to build something better with Eclipse.

**Comment by scharf** [comment]
Doug, I think you miss the point. It is not about using vi and sublime. It is about the I in IDE. Integrating does not mean re-implementing it in the IDE. Parsers that can run outside the IDE can be used in build tools and on the command line to automate things. 

In the past, I have been working on an IDE that hat a fantastic "integrated" build system. It was so "integrated" that it could not run without the IDE. But there was the request to run it on the command line. In the end, it was easier to create a new "fake" window system, that did not draw anything on the screen. All it did was, to allowed us to run the UI without any display run the IDE headless as a command line tool. There was too much I in the IDE.

This [bug entry](https://bugs.eclipse.org/bugs/show_bug.cgi?id=223131) makes me soooo sad. Eclipse still ships with support for Javascript 2 (1998). Javascript is part of the Eclipse for Java EE, the most downloaded package. And it only supports 17 year old javascript. That's a shame. 

If there would be a simple architecture that allows integrating external parsers, I am sure someone would have done it....

But I may be totally wrong. I can't live without IDE, But for web development, eclipse it no option for me. Therefore I use a jetbrains IDE which moves really fast. Even Xtext got [ported to InjelliJ](http://blog.efftinge.de/2014/10/eclipse-xtext-goes-intellij-idea.html). 

The only two things I really miss in the Jetbrains IDE is mylyn and a launcher like the [eclipse runner](https://github.com/scharf/eclipserunnerplugin/blob/master/EclipseRunner/help/Eclipse%20Runner.md), which allows me to manage my running processes. They have a launch bar and I hate it, but I guess your new launch bar is better than the jetbrains one.

**Comment by bruno-medeiros** [comment]
I'm with @scharf  on this one (mostly).

My experience with D, Go and Rust has shown me a clear trend to have external tools for semantic IDE features (code completion, etc.). And this trend exist for a good reason, not just because.

In today's world, there is not clear dominance in the IDE/editor market, it is still heavily fragmented: Many people use Eclipse, IntelliJ, VisualStudio, Netbeans, Sublime, and even (:scream::astonished:) vi/emacs. No clear leader amongst these. As such, it makes sense to have just one external tool instead of reimplementing everything from scratch for every IDE. As much as we love Eclipse, we have to recognize this is the best technical solution. Yes, using an external tool will incur either limitations in functionality (at first), or (subsequently) more development work on a more advanced communication protocol with the tool (one that would allow for as much functionality, nearly as fast, as if the semantic tool was part of the IDE itself). But that extra protocol work is quickly offset by the immense gains of having several people from other IDEs working on the external tool - because this tool would be quite complex.

A good example of this is https://github.com/RustDT/RustDT - this IDE is a volunteer project, less than 6 months old. Yet I was able to quickly provide Code Completion (and Find Definition) functionality on it, because an external tool was readily available to produce that, for Rust.

On another example, https://github.com/GoClipse/goclipse has made use of an external tool for code completion for a long time now, but used an internal parser for functionality like the editor outline. But the parser was significantly buggy and unmaintained - the original developer long gone -, so recently this functionality was switched to being provided by an external tool too ([Go oracle](http://golang.org/s/oracle-user-manual)).

The only thing I don't agree is about delegating lexing functionality (syntax highlighting for example) to an external tool. Lexing needs to happen incredibly fast, instantaneously really, so using an external tool seems like a big overhead. But more importantly, a language lexer is fairly simple and quick to write, it's like one or two orders of magnitude simpler to implement than a parser and/or semantic functionality like code completion. So it's not a big deal if every IDE/editor writes one.

**Comment by dschaefer** [comment]
I don't disagree with your comments. I'm just building something different than what you guys are talking about. I want to start with an Antlr 4 grammer and build an Eclipse-based IDE from it and ship it from Eclipse.org with EPL license and IP approvals. And do it quickly in stages starting with syntax highlighting then moving on to outline view, then references/definitions/declarations search and content assist, etc.

I just think we'll find that creating a grammar and hooking it up will be less work than wrapping an external parser, index and make it Eclipse friendly.

**Comment by scharf** [comment]
@dschaefer this sounds to me like Xtext started (as openArchitectureWare and it grew into Xtext). They started creating grammars using antlr. But over time they learned, that they added a bit more to antlr and they created their own EBNF like syntax that then created antlr code.

 Similarly, [Emfatic](https://wiki.eclipse.org/Emfatic) was based on someething called gymnast, which took a antlr grammar and generated an IDE.

LiClipse ist doing something similar. 

It sounds to me that this would add to the fragmentation of eclipse.

As a private playground fun project it may be great. But what would you do differently that the existing approaches?

**Comment by scharf** [comment]
@bruno-medeiros 

> The only thing I don't agree is about delegating lexing functionality (syntax highlighting for example) to an external tool.
> Lexing needs to happen incredibly fast, instantaneously really, so using an external tool seems like a big overhead. 

More than 20 years ago it was incredibly fast. Why would it be slow today when our computers are 100 times faster? I don't get this.... Well, maybe because nobody cares about speed anymore.

**Comment by bruno-medeiros** [comment]
> More than 20 years ago it was incredibly fast. Why would it be slow today when our computers are 100 times faster? I don't get this.... Well, maybe because nobody cares about speed anymore.

If a properly designed client-server system is created (I mean client-server as in inter-process communication, not network, of course), then yeah, I guess delegating lexing functionality to an external tool could be just as fast as otherwise. But it would have to a well designed system, and it would have to be IPC - merely starting a command-line tool for every keystroke would not be guaranteed to be fast enough on every OS, for a variety of reasons.

So who is going to bother writing such a system, when an IDE syntax highlighter can be written in around 100 _lines_ of code or so?

**Comment by scharf** [comment]
> So who is going to bother writing such a system, when an IDE syntax highlighter can be written in around 100 lines of code or so?

If it's that easy then I have a job for you: [Javascript support for eclipse](https://bugs.eclipse.org/bugs/show_bug.cgi?id=223131) 

If the architecture is done right, the parser creates a DOM and the DOM is used by the IDE. If there is an API for the DOM (and that can be really simple) then it does not matter if it is in process or out of process. All you have to do is to proxy the API calls. If you look at the [python parser I wrote 20 years ago](https://gist.github.com/scharf/a9e7a1ab41faf0896a96), you will see that the actual API was very simple. In this example the parse did not even keep the DOM in memory, it used a builder pattern to create the DOM...

**Comment by bruno-medeiros** [comment]
> If it's that easy then I have a job for you: Javascript support for eclipse

I mentioned _lexing_ and _syntax highlighting_, which you seem to be confusing with _parsing_, and other language support functionality. All these terms have specific meanings, and they mean very different things. It's important to use correct terminology.

Again, _lexing_ for a language is very easy and quick to implement, but _parsing_ is an order of magnitude harder (depending on the language of course - LISP is trivial, while C++ is crazy hard). And then after that, semantic functionality (code completion, find definition, _semantic_ highlighting, etc.) is another layer of work that is as hard, or harder, than _parsing_ (again depending on the language).

**Comment by scharf** [comment]
> I mentioned lexing and syntax highlighting, which you seem to be confusing with parsing

There are different levels of language support:
- syntax highlighting
- code navigation (including class hierarchies and call trees)
- code completion
- refactoring
  - renaming
  - ... more sophisticated stuff

For sophisticated refactoring, you need a full DOM. For navigation and code completion, there is a common misconception that you also need a full DOM. To be "perfect", you may need a full DOM and for statically typed languages with a well defined module system (Java, Scala..) this is actually a great goal.

Even a perfect parser for scripting languages is not sufficient to do perfect code completion and code navigation. 

I remember that Marcel Bruch explained that CodeTrails originally used a sophisticated DOM analysis and then they discovered that a simple heuristics based approach got similar results.

For code navigation, it is not necessary create a DOM with all expression details. It is just enough if you know declarations and scope of names. When I started working on IDEs Walter Bishofberger invented a concept called [fuzzy parsing](http://www.ubilab.org/publications/print_versions/pdf/sniff_usenix_92.pdf). The fuzzy parsing allowed to give hints to the parser how interpret some constructs. For example, C often uses complicated macros and the exact content of the macros is not interesting. The interesting part is the 'meaning' of those macros. So, the fuzzy parser allowed give replacement statements for some constructs to improve the code navigation experience and not to pollute the class hierarchy with low level stuff that is created by macros and is actually invisible in the code for a user.

In javascript there are often conventions that link pieces of code together that are not detected by the parser. There are often names used to link pieces of code together. And of you go cross language it can be that a javascript variable is called `foo_bar` which is linked to the HTML element `fooBar` which is linked to the CSS rule `foo-bar`.

To make a long story short, I think there is a big misconception to believe that there is syntax highlight and the next step in IDE support is a fully detailed DOM. Forget prefect parsing and the perfect DOM. Use heuristics that represent the developers view of the software instead of being 'pixel perfect'.

You may have seen my blogs on this topic [Evolution: form Emacs to Eclipse to IntelliJ and back to Emacs?](http://michaelscharf.blogspot.de/2014/03/evolution-form-emacs-to-eclipse-to.html) and [How to make eclipse attractive to new communities?](http://michaelscharf.blogspot.de/2014/05/how-to-make-eclipse-attractive-to-new.html)

**Comment by scharf** [comment]
@dschaefer I just discovered this paper by Walter Bischofberger form 1992 [Sniff—A Pragmatic Approach to a C++ Programming Environment](http://www.ubilab.org/publications/print_versions/pdf/sniff_usenix_92.pdf). Walter was part of the team around Erich Gamma. If you look at Erichs new baby VC Code you may find some ideas that emerged in the early 90ies. After reading the paper after such a long time, I realized how much that mind set still influences my view on IDEs. 

If you have the time I strongly recommend reading this paper.  Although it is quite old, I think the architectural decisions they made for sniff are still very valid today. What you you think?

**Comment by dschaefer** [comment]
Sorry, was busy for the last few days. Again, I like what you guys are saying and I'd love to see you build it so we can be sure that performance going over JNI, or through and RPC mechanism would be fast enough and easy to build.

But again, I'm focused on Antlr 4, and Antlr 4 specifically. It's come a very long way from Antlr 3 even. Xtext may have created their own grammar language to overcome deficiencies in earlier Antlr's but they never did do semantic predicates and seem unwilling to do so. And Antlr 4 provides automatic ambiguity resolution that does the right thing.

Xtext has now fallen way behind. And really, having experience using it you end up overriding everything because it doesn't do things the way that makes the most sense at times. There is a presentation on the web on a company that did JavaScript with Xtext and had to swap out much of the underlying engine to make it work. The Antlr4 JavaScript grammar, which has a small number of semantic predicates, just works.

And I want the system to work for hard languages such as C++ itself all the way down to HTML with embedded scripting languages such as TypeScript. I want to be in a position where with a few nights work we can start adding a new language.

To that end, I'm going to rename this project Antlng to avoid any confusion what I'm building. I encourage you guys to start a project and build something that works with external parsers and index databases. At the end, we can compare.

**Comment by scharf** [comment]
Doug, it's great to make clear that the scope is to be a project for your Antlr4 experiments! Eclipse is the right place for such experiments - it's already a blooming place and the grave for many of experiments and a bit more fragmentation does not harm ;-).

**Comment by bruno-medeiros** [comment]
@dschaefer Yup, it's clear some of the discussion between me and @scharf is pretty much off-topic to this issue, sorry about that. And we still have to hear what Fabio Zadrozny has to say. Perhaps another reason it would be nice to have a forum for all the interested parties working on similar projects?

@scharf I'm not entirely sure what you meant by perfect/full and non-perfect DOM. My instinct here is that you mean a "perfect DOM" would be an AST which contains all the necessary information to perform compilation of the source code (basically what the compiler does). This should probably be called AST, not DOM. (DOM is just an API on how you present a hierarchical model - an AST, XML, HTML, etc.)

If so, yes, you don't need a perfect/full AST to perform certain IDE functionality like code navigation or code completion. I know this well, since I've written from scratch a parser for the D language, as well as functionality to do open definition, code completion, etc. (The [DDT IDE](https://github.com/bruno-medeiros/DDT/) does not use an external tool, but this internal parser and semantic engine that I've wrote). This symbol resolution is not as accurate as the compiler (not even close!), but it doesn't have to be 100% accurate to be useful to the IDE user, yes.

But my point was, even an non-perfect parser + semantic functionality is a lot of work to write, for any non-trivial language.

**Comment by dschaefer** [comment]
We do have a forum. It's ide-dev@eclipse.org. This discussion is appropriate there.

**Comment by scharf** [comment]
@dschaefer you are right! Maybe we should close this issue.....

**Comment by bruno-medeiros** [comment]
> We do have a forum. It's ide-dev@eclipse.org. This discussion is appropriate there

Nice. I didn't know about that ML, will subscribe. (hope it's not too focused on the just the Eclipse.org projects side of things though)

**Comment by dschaefer** [comment]
We'll have to discuss that too. Ideally, these frameworks are part of the Eclipse platform so that all adopters in the community can use and contribute to them. Like to understand your reasons for not wanting it there so we can work with the Foundation on removing those hurdles.

**Comment by dschaefer** [comment]
At the end of the day, I have too many projects on the go. I'll start working on the QML editor for CDT and use ANTLR 4 for it. I'll do it so I can easily extract bits that can be reused by other languages. And I'll learn a lot more by doing a real language that will serve to prove or disprove the strategy.

**Comment by scharf** [comment]
:+1:
